version: "3.7"

services:

  krakend:
    image: devopsfaith/krakend:latest
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    volumes:
      - "${PWD}:/etc/krakend"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"
      - "14268:14268"

networks:
  default:
    name: multi-lang-network
    external: true