## defaults for _all_ profiles
[default]
address = "127.0.0.1"
port = 50013
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP" # set to `false` to disable
log_level = "critical"
temp_dir = "/tmp"
cli_colors = true
secret_key = "hPrYyЭRiMyµ5sBB1π+CMæ1køFsåqKvBiQJxBVHQk="
key = "a release app-key"
extra = false
template_dir = "api/templates/"


[default.databases.sea_orm]
# Mysql
# make sure to enable "sqlx-mysql" feature in Cargo.toml, i.e default = ["sqlx-mysql"]
url = "mysql://root:mypass@localhost/rocket_example"

# Postgres
# make sure to enable "sqlx-postgres" feature in Cargo.toml, i.e default = ["sqlx-postgres"]
#url = "postgres://user:pass@localhost:5432/rocket"
