version: "3.8"

services:

  # consul
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    command: "agent"

  # kong
  kong-db:
    container_name: kong-db
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./kong/pg_data:/var/lib/postgresql/data/

  kong-migrations:
    container_name: kong-migrations
    image: kong/kong-gateway:3.5.0.1
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
    command: kong migrations bootstrap

  kong-server:
    container_name: kong-server
    image: kong/kong-gateway:3.5.0.1
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    env_file:
      - ./.env

  # keycloak
  keycloak-db:
    container_name: keycloak-db
    image: mysql:8
    restart: always
    command: [ "mysqld", "--port=3307", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    ports:
      - "3307:3307"
    env_file:
      - ./.env
    volumes:
      - ./keycloak/db/data:/var/lib/mysql

  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:22.0.5
    restart: always
    ports:
      - "9443:9443"
    env_file:
      - ./.env
    volumes:
      - ./keycloak/app:/etc/x509/https # map certificates to container
    depends_on:
      - keycloak-db
    command: [ 'start --hostname localhost --https-port 9443' ]

networks:
  default:
    name: multi-lang
    external: true
