version: "3.7"

services:
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:latest
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    volumes:
      - "${PWD}/krakend:/etc/krakend"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"
      - "14268:14268"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - "${PWD}/keycloak:/etc/x509/https" # map certificates to container
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB: mysql
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    depends_on:
      - mysql
    command:
      - 'start --hostname localhost'
    env_file:
      - ./.env

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: hello-network
    external: true

