version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: api:${API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      API_HOST: 0.0.0.0
      API_DB_HOST: api-db
      API_DB_PORT: 5432
      API_DB_USER: api
      API_DB_PASS: api
      API_DB_BASE: api
      API_RABBIT_HOST: api-rmq
      API_REDIS_HOST: api-redis

  db:
    image: postgres:13.8-bullseye
    hostname: api-db
    environment:
      POSTGRES_PASSWORD: "api"
      POSTGRES_USER: "api"
      POSTGRES_DB: "api"
    volumes:
    - api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U api
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: api:${API_VERSION:-latest}
    restart: "no"
    command: aerich upgrade
    environment:
      API_DB_HOST: api-db
      API_DB_PORT: 5432
      API_DB_USER: api
      API_DB_PASS: api
      API_DB_BASE: api
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "api-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50



volumes:
  api-db-data:
    name: api-db-data
