version: "3.8"

services:

  # consul
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    command: "agent"

  # traefik
  traefik:
    container_name: traefik
    image: traefik:v2.5
    restart: always
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
#      - ./traefik/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - jaeger
      - consul-server

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  # jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"

  # keycloak
  keycloak-db:
    container_name: keycloak-db
    image: mysql:8
    restart: always
    command: [ "mysqld", "--port=3307", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    ports:
      - "3307:3307"
    env_file:
      - ./.env
    volumes:
      - ./keycloak/db/data:/var/lib/mysql

  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:22.0.5
    restart: always
    ports:
      - "8443:8443"
    env_file:
      - ./.env
    volumes:
      - ./keycloak/app:/etc/x509/https # map certificates to container
    depends_on:
      - keycloak-db
    command: [ 'start --hostname localhost' ]

networks:
  default:
    name: multi-lang
    external: true
