[package]
name = "referral"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
tokio = { version = "1.34.0", features = ["full", "tracing", "macros", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.10", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }

tonic = { version = "0.9.2", features = ["gzip"] }
tonic-health = "0.9.2"
tonic-types = "0.9.2"

futures = { version = "0.3.29", default-features = false, features = ["thread-pool"] }
async-stream = { version = "0.3.5"}
async-trait = "0.1.74"
once_cell = "1.19.0"

bytes = "1.5.0"
listenfd = { version = "1.0.1" }
rand = "0.8.5"
chrono = "0.4.31"
uuid = "1.6.1"
dotenvy = "0.15.7"
colored = "2.0.4"

prost = "0.11.9"
prost-derive = "0.11.9"
prost-types = { version = "0.11.9" }
serde = { version = "1.0.193", features = ["derive"] }
serde_derive = "1.0.193"
serde_json = "1.0.108"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
strum = "0.25.0"
strum_macros = "0.25.3"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt", "ansi", "env-filter", "tracing-log"] }


http = "0.2.11"
httparse = "1.8.0"
httpdate = "1.0.3"

[build-dependencies]
tonic-build = "0.9.2"

[[bin]]
name = "referral"
path = "src/main.rs"
