edition = "2021"
format_code_in_doc_comments=true
fn_call_width=120
max_width=180
array_width=120
chain_width=120
use_small_heuristics="Max"
reorder_imports = true
merge_imports = true
imports_layout = "HorizontalVertical"