[package]
authors = ["jason <jason@jaasun.com>"]
edition = "2021"
license = "MIT"
name = "c-portal"
publish = false
version = "0.1.0"

[workspace]
members = [".", "api", "shared"]

[dependencies]
api = { path = "api" }
shared = { path = "shared" }

